data_path: './data/Clothing1M_org'
dataset: 'Clothing1M'
alpha: 0.5
num_epochs: 200
num_class: 14
lr: 0.005
lr_f: 5e-5
batch_size: 128
warm_up: 20
num_samples: 100000
lambda_p: 100
Tu: 0.2
pretrained: true