data_path: '../../dataset/webVision/'
dataset: 'mini_WebVision'
num_epochs: 120
num_class: 50
lr: 1e-2
lr_f: 2e-5
batch_size: 24
warm_up: 10
num_samples: 65944
lambda_p: 50

alpha: 0.5
flow_modules: 32-32-32-32
weight_decay: 1e-4
cond_size: 512  #384 = 1536 / 4
isRealTask: True
centering: True
center_momentum: 0.8
decay: 0.99

T: 0.5

sharpening: 'UNICON'
Tf_warmup: 1.0
Tf: 0.7
flow_sp: False
jumpRestart: True
clip_grad: False