data_path: './data/tiny-imagenet-200'
dataset: 'TinyImageNet'
alpha: 0.5
num_epochs: 400
num_class: 200
lr: 0.05
lr_f: 2e-6
batch_size: 32
warm_up: 20
num_samples: 100000
lambda_p: 100
Tu: 0.5
alpha: 2
flow_modules: 256-256-256-256