data_path: './data/tiny-imagenet-200'
dataset: 'TinyImageNet'
num_epochs: 200
num_class: 200
lr: 4e-2
lr_f: 4e-5
batch_size: 256
warm_up: 15
num_samples: 100000
lambda_p: 100
Tu: 0.5
alpha: 2
flow_modules: 512-512-512-512
weight_decay: 5e-4
