data_path: './data/tiny-imagenet-200'
dataset: 'TinyImageNet'
alpha: 0.5
num_epochs: 200
num_class: 200
lr: 4e-2
lr_f: 4e-5
batch_size: 256
warm_up: 15
num_samples: 100000
flow_modules: 160-160-160-160
weight_decay: 5e-4
lambda_u: 50
linear_u: 16
cond_size: 512 # 2048/ 4
centering: True
center_momentum: 0.8
T: 0.2
flow_sp: False
clip_grad: True
d_u: 0.7