data_path: '../../dataset/webVision/'
dataset: 'WebVision'
num_epochs: 120
num_class: 50
lr: 0.01
lr_f: 2e-5
batch_size: 24
warm_up: 10
lambda_p: 50
alpha: 0.5
flow_modules: 256-256-256-256
cond_size: 384  #384 = 1536 / 4
isRealTask: True
num_samples: 65944
weight_decay: 1e-4
clip_grad: True

centering: True
center_momentum: 0.8
decay: 0.99

T: 0.5

sharpening: 'UNICON'
Tf_warmup: 1.0
Tf: 0.7

flow_sp: False
jumpRestart: True